dockerfile, first db creation, search example
Drakulix/knex pull request #10
Opened 2017-05-14 11:18 UTC by DubbleClick

2017-05-15 12:15 UTC, Drakulix requested changes
We probably only need the `Dockerfile` for our own python webserver (that container should be based on the official [`python` docker image](https://hub.docker.com/_/python/) and the rest of the services in a [`docker-compose.yaml`](https://docs.docker.com/compose/).

The `first.py` is a good start and helpful, but please use a proper name (maybe main.py) and create a folder for it. (See #6)

2017-05-15 12:15 UTC, Drakulix commented on Dockerfile
> +FROM microsoft/windowsservercore as msi
Why are we using a windows image as a base? Does this even work outside of windows?

2017-05-15 12:15 UTC, Drakulix commented on Dockerfile
> +
There is already a mongo docker image, no need to replicate it https://hub.docker.com/_/mongo/

2017-05-16 08:47 UTC, Drakulix commented on Dockerfile
> +
```
Step 1/22 : RUN pip install pymongo
Please provide a source image with `from` prior to run
```

Cannot even test it..

2017-05-16 11:18 UTC, DubbleClick commented
updated

2017-05-16 13:27 UTC, Drakulix requested changes
Thanks! Looks already very good. Just some nitpicks and smaller details.

2017-05-16 13:27 UTC, Drakulix commented on LICENSE
> -MIT License
ähm, the license is not an "unnecessary file".
Your first commit does not seem right.
Please try to do the following steps:

```
git checkout master
git pull
git checkout DubbleClick-patch-1
git rebase -i master
```

And remove your [last commit](6cf8cd0bd00f9ca61d1350be19386f2fb7e2bb1b) (skip) from the rebase.
Also please skip all commits, that are already part of master (all travis related commits) and then fix any remaining conflicts, if any (should all be fine).

2017-05-16 13:27 UTC, Drakulix commented on docker-compose.yml
> +        build: ./mongodb
This is unnecessary. You can just do `image: mongo`, that's it.

2017-05-16 13:27 UTC, Drakulix commented on docker-compose.yml
> +            - 27017:27017
Unnecessary, please see the next comment.

2017-05-16 13:27 UTC, Drakulix commented on docker-compose.yml
> +            - 8000:27017
Please just do:

```
links:
    - mongodb-service
```
to automatically route all mongodb ports to only the python container and just open the port of the outgoing webserver port of flask.

2017-05-16 13:27 UTC, Drakulix commented on docker-compose.yml
> +            - mongodb-service
Please add a trailing new line

2017-05-16 13:27 UTC, Drakulix commented on mongodb/Dockerfile
> +# Pull base image.
File is unnecessary (see comment regarding `image:` key in docker-compose.yml)

2017-05-16 13:27 UTC, Drakulix commented on pythonfile/Dockerfile
> +FROM python:3.6.1
Please use `3` instead of `3.6.1`.

2017-05-16 13:27 UTC, Drakulix commented on pythonfile/requirements.txt
> +pymongo
:+1:

2017-05-16 13:27 UTC, Drakulix commented on pythonfile/Dockerfile
> +CMD ["python", "first.py"]
Example taken from the python docker image [hub website](https://hub.docker.com/_/python/):

```
FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "python", "./your-daemon-or-script.py" ]
```

By coping you can get the source files into the image (also fixing your windows problem / see slack) and redistribute our whole app as a container.
Also running `pip` will install all dependencies.

2017-05-17 08:44 UTC, Drakulix submitted a review, later dismissed
Great!

You git history still seems a little confusing, although all files are here.
(I will fix that myself and merge asap)

2017-05-17 09:00 UTC, Drakulix approved these changes
@DubbleClick I have rebased your work. Can you check, that everything is still there?

Afterwards it's ready for merge.

2017-05-17 10:20 UTC, merged