users collection setup and insert_user()
Drakulix/knex pull request #121
Opened 2017-06-09 15:22 UTC by aTepliak

collection for user login and registration data, and prototype insert_user()

2017-06-09 15:35 UTC, Drakulix requested changes
Good start. Please remove the pycache files. :)

2017-06-09 15:35 UTC, Drakulix commented on backend/flask_api.py
> +def insert_user(firstname, lastname, email, password_hash,bio="",bookmarks=""):
Could you refactor this in an endpoint call? PUT /api/users?

2017-06-10 11:01 UTC, DubbleClick commented on backend/flask_api.py
> +    return  make_response('', 404)
please fix

2017-06-10 11:01 UTC, DubbleClick commented on backend/flask_api.py
> +        "password_hash": password_hash, #bcrypt.hashpw(password_hash.encode('utf-8'), bcrypt.gensalt()),
this line is too long to pass pep-8

2017-06-11 21:57 UTC, DubbleClick commented
seeing as we want to use flask-security for the user and login system I do not think we can use the database to handle users like this. see flask-mongoengine and flask-security mongoengine introductions as example

2017-06-14 09:01 UTC, closed without merging