hotfix for #128
Drakulix/knex pull request #132
Opened 2017-06-10 21:41 UTC by DubbleClick

2017-06-10 21:45 UTC, Drakulix submitted a review, later dismissed
Looks good!

2017-06-10 21:49 UTC, Drakulix submitted a review, later dismissed

2017-06-10 22:05 UTC, DubbleClick commented
@Leats please test if this works

2017-06-10 22:16 UTC, Drakulix requested changes

2017-06-10 22:16 UTC, Drakulix commented on backend/flask_api.py
> +            return make_response("Error: " + str(err), 500)
This should not be necessary. An uncatched exception always results in a 500 with the appropriate message, please remove.

2017-06-10 22:30 UTC, Leats approved these changes
test_empty_post does pass, doesn't let any other previously successful tests fail. Looks good!

2017-06-11 11:05 UTC, Drakulix approved these changes

2017-06-11 11:05 UTC, merged