Backend/user api endpoints/iss113
Drakulix/knex pull request #148
Opened 2017-06-13 16:15 UTC by pdler

Everything should work ...

2017-06-13 20:51 UTC, henderkes requested changes

2017-06-13 20:51 UTC, DubbleClick commented on backend/.idea/backend.iml
> +    <orderEntry type="jdk" jdkName="Python 3.5.3 (/usr/bin/python3.5)" jdkType="Python SDK" />
hardcoding the python version to 3.5.3 does not seem to be a good idea to me

2017-06-13 20:53 UTC, henderkes requested changes

2017-06-13 20:53 UTC, DubbleClick commented on backend/flask_api.py
> +coll_user = db.user
wait, why?

2017-06-13 20:53 UTC, DubbleClick commented on backend/flask_api.py
> +    user_datastore.create_user(email='user@knex.com', password=pbkdf2_sha256.hash("user"), roles=[user_role])
this is how users are created, what is the db.users collection for?

2017-06-14 17:02 UTC, Drakulix requested changes
Additional tasks:

- [ ] Allow only users to replace their project now that #147 is merged
- [ ] Make Project upload @login_required
- [ ] Make project delete @admin required
- [ ] Comment out all @admin/login_required annotations for merge, so we have time to fixup travis, write tests and for the frontend to catch up until we enable this requirement.

2017-06-14 17:02 UTC, Drakulix commented on backend/.idea/backend.iml
> +<?xml version="1.0" encoding="UTF-8"?>
please add `.idea` to your .gitignore

2017-06-14 17:02 UTC, Drakulix commented on backend/flask_api.py
> +from passlib.hash import pbkdf2_sha256
See #163

2017-06-14 17:02 UTC, Drakulix commented on backend/flask_api.py
> +@roles_required('admin')
Allow a user to update itself

2017-06-14 17:04 UTC, Drakulix commented on backend/flask_api.py
> +@roles_required('admin')
Also this should be `/api/users/<email>` to be really RESTful

2017-06-14 17:04 UTC, Drakulix commented on backend/flask_api.py
> +            return make_response('User already exists',500)
Please make this a `400` for `Bad Request` instead of a 500.

2017-06-15 17:29 UTC, DubbleClick commented
Please take a look at drakulix' requested changes and also pay attention to pep8 (in /knex/ directory execute "pip install pep8" and then "pep8 ."

2017-06-15 20:12 UTC, DubbleClick commented
with the default users removed we'll need an initialisation script to create at least one admin user

2017-06-16 15:04 UTC, henderkes requested changes
please remove __pycache__ stuff, merge current master into this branch and fix pep8 coding conventions, it will be easier to have a detailed look then

2017-06-16 15:04 UTC, DubbleClick commented on backend/flask_api.py
> +        return make_response('Username oder Password invalid', '500')
please don't pass the status code as string but as integer

2017-06-18 11:24 UTC, pdler commented
ready to merge..

2017-06-18 12:05 UTC, Drakulix requested changes
Almost perfect

2017-06-18 12:05 UTC, Drakulix commented on backend/flask_api.py
> +    pw = encrypt_password("user")
`create_user` already encrypts the password, this call should only be needed for the update call, where we directly set the password.

2017-06-18 12:05 UTC, Drakulix commented on backend/flask_api.py
> +    pw = encrypt_password("admin")
See above

2017-06-18 12:05 UTC, Drakulix commented on backend/flask_api.py
> +                                   password=encrypt_password(user["password"]),
See above

2017-06-18 13:30 UTC, pdler commented on backend/flask_api.py
> +    pw = encrypt_password("user")
No it does not seem so...
If I remove the encrypt_password function, the password is stored as plaintext....(SECURITY_PASSWORD_HASH and SECURITY_PASSWORD_SALT are set...)

2017-06-18 16:58 UTC, Drakulix submitted a review, later dismissed

2017-06-18 16:58 UTC, Drakulix commented on backend/flask_api.py
> +    pw = encrypt_password("user")
Seems you are right, this is a little weird, but okay.

2017-06-18 19:27 UTC, DubbleClick commented on backend/flask_api.py
> +                 and no files attached", 400)
pep8 discourages line breaks in statements and encourages (same line) operators instead

2017-06-18 19:27 UTC, DubbleClick commented on backend/flask_api.py
> +            "*(@|\sat\s)(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?"+\
I think there is no reason for the backslash here, operators should come with a single whitespace

2017-06-18 19:27 UTC, DubbleClick commented on backend/flask_api.py
> -
??? please keep that in, the encouraged form is:

-absolute imports- (import library)

-relative imports- (from library import X)

-own absolute imports- (import projectfile)
-own relative imports- (from projectfile import X)

2017-06-18 19:27 UTC, DubbleClick commented on backend/flask_api.py
> +
this is a line break too much, pep8 again

2017-06-18 19:32 UTC, DubbleClick commented
The code looks good now, but I don't think we should merge this with so many "discouraged styling issues". You also import json5 twice, line breaks are missing or too much, Backslash operator is used very often though discouraged. I will fix these myself now but we should pay more attention in the future, given that we promised a consequent coding style.

2017-06-18 20:04 UTC, DubbleClick commented
The code looks good now, but I don't think we should merge this with so many "discouraged styling issues". You also import json5 twice, line breaks are missing or too much, Backslash operator is used very often though discouraged. I will fix these myself now but we should pay more attention in the future, given that we promised a consequent coding style.

2017-06-18 20:11 UTC, henderkes submitted a review, later dismissed

2017-06-18 21:06 UTC, henderkes approved these changes
added comments

2017-06-18 21:06 UTC, merged