Flask api
Drakulix/knex pull request #15
Opened 2017-05-23 17:08 UTC by svirovsk

The api has the three main endpoints  (add_project, get_project_by_id and search) plus delete_project and index, which returns the first project imported via create_project().
I've tried to test the endpoints with curl. index(), get_project_by_id(id) and delete_project() work. The request for add_project() is kind of long (the whole jsonstring) and I haven't tested it yet, but it's more or less the same as in create_project() and that one works. It adds date_created and date_published to the jsonstring, validates it and adds an uuid at the end. The functions don't handle errors yet.
Unfortunatelly, I can't run the docker container with elasticsearch, so it'll be nice if someone of you runs it and tells me if it works. Here, I'm not sure again how to design the curl request.
I haven't run the container with all changes and there might be other errors as well.

2017-05-23 17:29 UTC, Drakulix requested changes
Generally already very good, I have requested some smaller changes.

Also we should try to design a RESTful API. While this is okay and supports all required use cases, I recommend to read [this article](http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#requirements), especially the very first paragraph (the rest does only partly apply to our current situation, but is still a rather good read).

I would suggest to change the api endpoints as follows:

```
GET /api/projects (list of projects - not required, but would be nice later, so I document that here)
POST /api/projects (upload manifest, return uuid of created project on success, error message else)
GET /api/projects/<id> (get project by id)
DELETE /api/projects/<id> (delete project by id)
POST /api/projects/search (elasticsearch endpoint)
```

The api prefix is suggested, because the frontend will most likely be served on the index. This way we can easily differentiate between the two.

Those are only suggestions and we can move them to separate issue, if time is short, they do not block the merge of this request (the requested changes do), although I would certainly like to see those rather soon then later.

2017-05-23 17:29 UTC, Drakulix commented on pythonfile/Dockerfile
> +CMD [ "python", "./first.py", "./flask-api.py" ]
Was this tested? Does this work that way?

2017-05-23 17:29 UTC, Drakulix commented on pythonfile/flask_api.py
> +@app.before_first_request
Please remove this `^M` character

2017-05-23 17:29 UTC, Drakulix commented on pythonfile/flask_api.py
> +def create_project():
Is this some kind of test data?

2017-05-23 17:29 UTC, Drakulix commented on pythonfile/flask_api.py
> +@app.route('/', methods=['GET','POST'])
Also for testing?

2017-05-23 17:29 UTC, Drakulix commented on pythonfile/flask_api.py
> +@app.route('/add_project')
What happens if I do a `GET` request here? Should this be `POST` only?

2017-05-23 17:29 UTC, Drakulix commented on pythonfile/flask_api.py
> +    r = validator.validate_manifest(manifest)
What is `r`? If it can contain an error, please write it to `stderr` for the moment.

2017-05-23 17:29 UTC, Drakulix commented on pythonfile/flask_api.py
> +@app.route('/get_project_by_id/<uuid:project_id>', methods=['GET','POST'])
This should be `GET` only.

2017-05-23 17:29 UTC, Drakulix commented on pythonfile/flask_api.py
> +@app.route('/delete_project/<uuid:project_id>')
Again what method? I assume `POST` or `DELETE`?

2017-05-23 17:29 UTC, Drakulix commented on pythonfile/manifest_validator.py
> +        except FileNotFoundError:
How is this error possible, if `json_manifest` is a string? Can `json5.load()` also accept filenames?
Or is this a left-over?

2017-05-23 17:33 UTC, Drakulix commented on pythonfile/flask_api.py
> +    r = validator.validate_manifest(manifest)
Or better write that to the response.body

2017-05-23 17:50 UTC, svirovsk commented on pythonfile/flask_api.py
> +@app.before_first_request
Well, I don't know how. I don't see it, when I try to edit it. Even if I write it again, it doesn't see the changes

2017-05-23 17:51 UTC, svirovsk commented on pythonfile/flask_api.py
> +def create_project():
yes, it was supposed to be

2017-05-23 18:07 UTC, svirovsk commented on pythonfile/flask_api.py
> +@app.route('/add_project')
By default it just listens for GET requests, but of course, I can explicitly define the methods

2017-05-23 19:33 UTC, svirovsk commented on pythonfile/flask_api.py
> +@app.route('/delete_project/<uuid:project_id>')
I suppose `DELETE` is fine, but what should the function return?

2017-05-23 20:41 UTC, Drakulix requested changes
Great, much much better.

2017-05-23 20:41 UTC, Drakulix commented on pythonfile/flask_api.py
> +@app.route('/api/projects', methods=['DELETE'])
What happens if project_id is not given here?

2017-05-23 20:41 UTC, Drakulix commented on pythonfile/flask_api.py
> +    return jsonify(coll.delete_one({'_id':project_id}).raw_result)
jsonify? This does not seem right, I will search for a better solution

2017-05-24 10:17 UTC, Drakulix submitted a review, later dismissed

2017-05-24 10:30 UTC, Drakulix approved these changes
Updated

2017-05-24 11:03 UTC, merged