Test security/iss165
Drakulix/knex pull request #184
Opened 2017-06-20 19:45 UTC by aTepliak

tests for flask security functions

2017-06-20 20:58 UTC, henderkes requested changes

2017-06-20 20:58 UTC, DubbleClick commented on .idea/codeStyleSettings.xml
> +<?xml version="1.0" encoding="UTF-8"?>
remove this file please and then add *.idea to the .gitignore

2017-06-20 20:58 UTC, DubbleClick commented on tests/api/test_security.py
> +    def setUp(self):
no camelCase allowed, please change this to setup(self) or set_up(self). Better yet would be __init__(self) though
https://docs.python.org/2/reference/datamodel.html#object.__init__

2017-06-20 20:58 UTC, DubbleClick commented on tests/api/test_security.py
> +        assert response.reason == 'INTERNAL SERVER ERROR'
This is very poor behaviour (not the test methods fault, but this has to be changed too), a login attempt with wrong user/password should not lead to an internal server error but a 400 code

2017-06-20 20:58 UTC, DubbleClick commented on tests/api/test_security.py
> +        assert response.status_code == 500
see above

2017-06-20 20:58 UTC, DubbleClick commented on tests/api/test_security.py
> +    def test_access_login_requiered_logged(self, pytestconfig, flask_api_url):
remove the "e" please, it's "required"

2017-06-20 20:58 UTC, DubbleClick commented on tests/api/test_security.py
> +                                 headers={'Content-Type': 'application/json5'})
nice :)

2017-06-20 20:58 UTC, DubbleClick commented on tests/api/test_security.py
> +'''
We currently use """ for multiline comments, "some string" for strings and 'variable' for directives and such

2017-06-20 21:22 UTC, Drakulix commented
@DubbleClick is right, otherwise this looks good! Thanks for tackling this.

2017-06-21 11:20 UTC, aTepliak commented
for logint/ fake login test, the "BAD REQUEST" with   400 code, should be returned in respective functions in flask_api.py.
Now there is  "Internal server error" with 500 code

2017-06-21 15:08 UTC, Drakulix commented
@aTepliak Your .idea files are still in there, but otherwise this looks good now. However we should fix the user endpoints before merging this.

2017-06-21 15:15 UTC, henderkes reviewed
couple more things, rest looks good!

2017-06-21 15:15 UTC, DubbleClick commented on tests/api/test_security.py
>          assert response.reason == 'INTERNAL SERVER ERROR'
This first assert has to removed or changed, too

2017-06-21 15:15 UTC, DubbleClick commented on tests/api/test_security.py
>          assert response.reason == 'INTERNAL SERVER ERROR'
This also shouldn't be an internal server error

2017-06-26 22:49 UTC, aTepliak commented on tests/api/test_security.py
>          assert response.reason == 'INTERNAL SERVER ERROR'
oki doki

2017-06-28 09:38 UTC, aTepliak commented
@DubbleClick  I removed the .idea files and travis fails in a very strange manner now

2017-06-28 10:00 UTC, DubbleClick commented
That's because the branch is not up to date with master, docker-engine no longer exists and therefore travis can't install it. Do you want me to rebase?

2017-07-02 10:07 UTC, DubbleClick commented
To revive this a bit if this should ever land in master I made some changes and cleaned up a little. The /api/users endpoints were a little broken too and I applied some fixes here. @aTepliak this still needs testing and further work, please continue with this as I have a few other issues to solve.

2017-07-02 10:12 UTC, henderkes requested changes
In general, should we allow admins to bookmark projects for other users? I guess not, but just to make sure.

2017-07-02 10:12 UTC, DubbleClick commented on backend/api/users.py
>          return make_response("Unknown User with Email-address: " +
I'm not even sure if this makes sense. It's the current_user anyway and this is @login_required so there is literally no chance that the user is unknown. If for any reason the user_datastore can't find the user (?) this should raise an internal server error / apiexception.

Other input is welcome, just my thought.

2017-07-02 10:12 UTC, DubbleClick commented on backend/api/users.py
> +    res = g.user_datastore.get_user(current_user.email.to_python())
is this even necessary? Can't we just use res = current_user? I don't see why not, get_user and current_user are both of type User(Document, UserMixin)

2017-07-17 19:56 UTC, closed without merging