Tests get all projects
Drakulix/knex pull request #186
Opened 2017-06-21 09:28 UTC by markwitz

added a test that tests if get all returns manifests and added some database cleanup

2017-06-21 15:05 UTC, Drakulix requested changes
Overall good stuff, just some questions and nitpicks.

2017-06-21 15:05 UTC, Drakulix commented on tests/api/conftest.py
> +    # files_before = # ... do something to check the existing files
This part of the comments seems copy&pasted and completely unrelated

2017-06-21 15:05 UTC, Drakulix commented on tests/api/test_database_connection.py
>      assert response.text == "There are no projects"
Although this test is correct, I am not certain this is the best way handle this case. I prefer the response to be an empty json array in that cases and the error code to be 200, could you quickly change that?

2017-06-21 15:05 UTC, Drakulix commented on tests/api/test_projects.py
> +        projects = response.json()
with your new yield_fixture will there be any contents in the db here?

2017-06-22 15:25 UTC, markwitz commented on tests/api/test_projects.py
> +        projects = response.json()
it should cleanup before the test and after the test

2017-06-22 15:53 UTC, Drakulix commented on tests/api/test_projects.py
> +        projects = response.json()
So then there are no projects in here, right? Whats the purpose of this test then.

2017-06-27 20:34 UTC, Drakulix submitted a review, later dismissed

2017-06-28 10:01 UTC, markwitz commented
fixing response coder for getprojects on empty database

2017-06-29 11:47 UTC, markwitz commented
@Drakulix could you rereview?

2017-06-29 16:35 UTC, Drakulix submitted a review, later dismissed
This looks nice now.

2017-06-29 16:36 UTC, Drakulix commented
@markwitz I apologize for the mess on the master currently, but could you rebase? I will then merge this asap. Looks fine now.

2017-06-30 18:18 UTC, DubbleClick commented
rebased this as it was only my changes this was conflicting with

2017-06-30 21:22 UTC, henderkes approved these changes

2017-07-01 15:58 UTC, merged