Refactor flask_api.py to use Blueprints
Drakulix/knex pull request #218
Opened 2017-06-21 20:26 UTC by Drakulix

This touches almost everything, but needs to be put into master asap so work can continue. Please review soon, but carefully and with caution.

2017-06-21 21:18 UTC, henderkes requested changes
travis doesn't run yet, but I didn't check what's wrong yet. pep8 will fail either way at the moment.

I like the project structure, +1

2017-06-21 21:18 UTC, henderkes commented on backend/__init__.py
> +def init_gloabl_mongoclient():
typo, please fix

2017-06-21 21:18 UTC, DubbleClick commented on backend/__init__.py
> +        VALIDATOR = Draft4Validator(schema, format_checker=FormatChecker())
this doesn't have to be called every request since it's a global, not member of flasks "g" object

2017-06-21 21:18 UTC, DubbleClick commented on backend/api/projects.py
> +    uploaded_files = request.files.getlist("file[]")
ehh, not on topic but before I forget it this should probably be 'file[]' to fit the rest of the code

2017-06-21 21:18 UTC, DubbleClick commented on backend/api/projects.py
> +                  or 500 in case of validation error
this should not return 500 (internal server error) in case of a validation error @Krisselchen can you fix this after this is in master?

2017-06-21 21:18 UTC, DubbleClick commented on backend/api/users.py
> +                                   bio=user["bio"], roles=[role])
under-indented

2017-06-21 21:18 UTC, DubbleClick commented on backend/api/users.py
> +def updateUser():
this should be update_user

2017-06-21 21:18 UTC, DubbleClick commented on backend/api/users.py
> +def getUser(mail):
and get_user

2017-06-21 21:18 UTC, DubbleClick commented on backend/api/users.py
> +def createUser():
create_user

2017-06-21 23:19 UTC, Drakulix commented
@DubbleClick should all be done now, pls check again.

2017-06-22 07:46 UTC, markwitz commented
when did we change travis setup to download like that `sudo apt-get -y -o Dpkg::Options::="--force-confnew` ? we need to fix that so we can be sure everything works fine

2017-06-22 07:49 UTC, markwitz reviewed
i really like the structure and the approach to init int the __init__ file I will approve once we fix travis

2017-06-22 07:49 UTC, markwitz commented on backend/__init__.py
> +        VALIDATOR = Draft4Validator(schema, format_checker=FormatChecker())
it says before first request

2017-06-22 10:18 UTC, henderkes reviewed
few more changes, then good to go

2017-06-22 10:18 UTC, DubbleClick commented on .travis.yml
> +group: edge
I wanted to suggest that 😠

2017-06-22 10:18 UTC, DubbleClick commented on backend/__init__.py
> +
two new lines seem to be a bit much after a comment? what does pep8 say there?

2017-06-22 10:18 UTC, DubbleClick commented on backend/api/projects.py
> +
I think we should remove the new lines at least here, the method should later be @login_required without new lines, it's not a section start as before.
It should actually be moved below the @projects.route() statement

2017-06-22 10:32 UTC, henderkes requested changes

2017-06-22 10:32 UTC, DubbleClick commented on backend/__init__.py
> +
relocate that above the app.register_blueprints please

2017-06-22 10:32 UTC, DubbleClick commented on backend/__init__.py
> +
same as before

2017-06-22 10:33 UTC, DubbleClick commented on backend/api/projects.py
> +@projects.route('/api/projects', methods=['POST'])
still the same as well

2017-06-22 10:35 UTC, Drakulix commented on backend/__init__.py
> +
Must be under the blueprint to not catch the api endpoints.

2017-06-22 10:47 UTC, DubbleClick commented on backend/api/projects.py
> +@projects.route('/api/projects', methods=['POST'])
swap the two lines, then it's good to go

2017-06-22 10:48 UTC, henderkes submitted a review, later dismissed

2017-06-22 10:50 UTC, henderkes approved these changes

2017-06-22 10:57 UTC, merged