[BE] WIP archive projects
Drakulix/knex pull request #246
Opened 2017-06-29 11:32 UTC by markwitz

- [ ] get all projects without archived 
- [ ] get one project without archived 
- [ ] get all archived projects 
- [ ] get one archived project
- [ ] unarchive project 
- [ ] filter ES search so it only returnes archved or not archived results
- [ ] Tested?
i implemented archiving as an optional field in the manifest 
default is to not display archived projects
archived projects will be displayed by using a different route

2017-06-29 16:34 UTC, Drakulix requested changes
Good stuff, but duplicating the /api/projects call is not the right way, I think.
This causes a lot of duplicated code, I would like to see the archived status being passed as an query string argument.

Similar to the search function where `limit` and `skip` are optional parameter, I would like to see an `archived` flag added to the existing endpoints, that can either be `true` or `false` and defaults to `false`.

2017-06-29 22:46 UTC, DubbleClick commented
Yeah those should be single methods with ['archived'] as an optional flag like in the manifest schema. This should be easily searchable in ES, too, I guess there should be a way to filter out archived results right in the search call.

2017-07-09 23:35 UTC, Drakulix submitted a review, later dismissed

2017-07-09 23:35 UTC, Drakulix commented on backend/api/projects.py
> +    if res is None:
:-1:

2017-07-09 23:36 UTC, Drakulix commented on backend/api/projects.py
> +    if res is None:
Not is objectively better in most cases.

2017-07-11 08:37 UTC, Drakulix requested changes
Just rebased (no conflicts) and reviewed this, could you do some small changes quickly @markwitz ? I will then merge this asap.

2017-07-11 08:37 UTC, Drakulix commented on backend/api/projects.py
> +        query = {}
This is actually unnecessary to do, because query is initialized empty anyway.

2017-07-11 08:37 UTC, Drakulix commented on backend/api/projects.py
> +import sys
Could you remove this and the debug prints again?

2017-07-11 08:37 UTC, Drakulix commented on backend/api/projects.py
> +    print(archived, file=sys.stderr)
See above

2017-07-11 08:37 UTC, Drakulix commented on backend/api/projects.py
> +        res = g.projects.find(query)
Since archived is set anyway via default, could this not be the final else clause?

2017-07-11 08:37 UTC, Drakulix commented on backend/api/projects.py
>          return make_response('Invalid parameters', 400)
See above, can this be reached? If not, it should be removed, as this can be confusing at first.

2017-07-11 08:37 UTC, Drakulix commented on backend/api/projects.py
> +        res = None
I don't this getting a project directly via Id should require archived to be set, now that we allow everybody to search in all archived projects. Could you revert this part?

2017-07-11 08:37 UTC, Drakulix commented on backend/api/projects.py
> +            #                        400, request.on_json_loading_failed())
Just delete this please.

2017-07-12 06:57 UTC, markwitz commented on backend/api/projects.py
> +        res = g.projects.find(query)
moved to checking for an allowed status for archived because i's a string to support mixed as an argument

2017-07-12 15:46 UTC, Drakulix submitted a review, later dismissed

2017-07-12 19:20 UTC, Drakulix approved these changes

2017-07-12 19:23 UTC, merged