Backend/bugfix/update/iss229
Drakulix/knex pull request #262
Opened 2017-06-30 18:25 UTC by pdler

added method that checks if a user has admin role. He can change a user (with user role) password without using the old password (maybe the user forgot his password)....

2017-06-30 18:33 UTC, henderkes requested changes

2017-06-30 18:33 UTC, DubbleClick commented on backend/api/helper/userpermission.py
> +        if(role.name == 'admin'):
we have @roles_required('admin') and @ADMIN_PERMISSION.require() for this

2017-06-30 18:33 UTC, DubbleClick commented on backend/api/helper/userpermission.py
> +def is_permitted(roles):
this method also needs the current user and the instruction it should compare the eligiblility to execute on

2017-06-30 18:33 UTC, DubbleClick commented on backend/api/users.py
> +    is_same_user = editor['email'] == user['email']
feel like this should be in the is_permitted method

2017-06-30 18:33 UTC, DubbleClick commented on backend/api/users.py
> +from bson.json_util import dumps
?

2017-06-30 18:33 UTC, DubbleClick commented on backend/api/users.py
> +    logout_user, current_user
?

2017-06-30 18:33 UTC, DubbleClick commented on backend/api/users.py
> +        if verify_password(old_password, res.password):
this check should not be needed if the current user is an admin. he could as well just create a different admin user, log in with that one and then change the password of his old user. doesn't make sense, really.

2017-06-30 18:53 UTC, pdler commented
I have no time to change this. I am in the frontend team (since wednesday) and I have to learn react for finishing the frontend tasks... So you can do the changes yourself or someone else.

2017-07-05 11:12 UTC, henderkes requested changes

2017-07-05 11:12 UTC, DubbleClick commented on backend/__init__.py
> +    UserMixin, RoleMixin, current_user
-

2017-07-05 11:12 UTC, DubbleClick commented on backend/api/users.py
> +from bson.json_util import dumps
-

2017-07-05 11:12 UTC, DubbleClick commented on backend/api/users.py
> +@login_required
-

2017-07-05 11:12 UTC, DubbleClick commented on backend/api/users.py
> +        if user['roles'] == 'admin':
not very nice but I guess we won't let the frontend change that

2017-07-05 11:12 UTC, DubbleClick commented on backend/api/users.py
> +                                         user['password']),
pep8

2017-07-05 11:12 UTC, DubbleClick commented on backend/api/users.py
> +        res = make_response(dumps(res))
why do we need dumps here, use jsonify

2017-07-05 11:12 UTC, DubbleClick commented on backend/api/users.py
> +        res.headers['Content-Type'] = 'application/json'
json5?

2017-07-05 11:12 UTC, DubbleClick commented on backend/api/users.py
> +    return make_response("You don't have the permissions " +
You don't have permission to edit this user.

2017-07-05 11:12 UTC, DubbleClick commented on backend/api/users.py
> +        if verify_password(old_password, res.password):
this still holds true, make it ```if current_user.has_role('admin') or verify_password(...)```

2017-07-05 11:12 UTC, DubbleClick commented on backend/api/users.py
> +    if current_user.has_role('admin'):
I would rather not write the same code twice but just solve it like I suggested above

2017-07-05 11:12 UTC, DubbleClick commented on backend/api/users.py
> +        return make_response("You don't have the permissions " +
You don't have permission to edit this user.

2017-07-05 11:36 UTC, merged