Backend/notification/iss194
Drakulix/knex pull request #280
Opened 2017-07-05 12:24 UTC by aTepliak

2017-07-05 22:42 UTC, henderkes submitted a review, later dismissed

2017-07-05 22:42 UTC, DubbleClick commented on backend/__init__.py
> +    ObjectIdField
please sum this up in a single import with braces ()

2017-07-05 22:42 UTC, DubbleClick commented on backend/__init__.py
> +            r"*(@|\sat\s)(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?" + \
please remove the whitespaces, lint (and pep8?) complain otherwise

2017-07-05 22:42 UTC, DubbleClick commented on backend/__init__.py
> +    notification_id = ObjectIdField(default=ObjectId)
missing DB. I think and ObjectId is not defined, is it?

2017-07-05 22:42 UTC, DubbleClick commented on backend/__init__.py
> +    g.notify_users = notify_users
ugh.... but probably the best we can do before the refactoring

2017-07-05 22:42 UTC, DubbleClick commented on backend/api/projects.py
>  from flask import request, jsonify, make_response, g, Blueprint
add a newline please

2017-07-05 22:42 UTC, DubbleClick commented on backend/api/projects.py
> +
and remove this one

2017-07-05 22:42 UTC, DubbleClick commented on backend/api/projects.py
>  projects = Blueprint('api_projects', __name__)
and include this one again

2017-07-05 22:42 UTC, DubbleClick commented on backend/api/projects.py
> -
see above

2017-07-05 22:42 UTC, DubbleClick commented on backend/api/projects.py
> +def share_via_email(user_mail):
project_id is missing as parameter I think

2017-07-05 22:42 UTC, DubbleClick commented on backend/api/projects.py
> +    link = "/projects/" + str(project_id)
is this the way the link looks at the frontend? I heard something different today

2017-07-05 22:42 UTC, DubbleClick commented on backend/api/projects.py
> +    if res is None:
"if not res" please

2017-07-05 22:42 UTC, DubbleClick commented on backend/api/projects.py
> +    link = "/projects/" + str(project_id)
see ^2 above

2017-07-05 22:42 UTC, DubbleClick commented on backend/api/users.py
> +                                     bio=user["bio"], roles=[role])
please revert this, the variable is still called "roles" and not "role".

2017-07-05 23:01 UTC, Drakulix commented on backend/__init__.py
> +    g.notify_users = notify_users
It's again a circular import, there is actual nothing else we can do about it.

2017-07-05 23:46 UTC, Drakulix commented on backend/api/projects.py
> +    link = "/projects/" + str(project_id)
It might, no idea

2017-07-05 23:48 UTC, Drakulix commented
@DubbleClick Probably won't have much more time for this. Would be nice if you could test and finish this, did some final touches.

2017-07-05 23:57 UTC, Drakulix commented on backend/api/users.py
> +                                     bio=user["bio"], roles=[role])
Changed the variable name instead.

2017-07-07 11:27 UTC, aTepliak commented on backend/__init__.py
> +    ObjectIdField
okay, hope with line breake \ is also ok

2017-07-07 11:28 UTC, aTepliak commented on backend/__init__.py
> +    notification_id = ObjectIdField(default=ObjectId)
no it is imported

2017-07-07 11:29 UTC, aTepliak commented on backend/__init__.py
> +            r"*(@|\sat\s)(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?" + \
have no idea, pycharm did it automatically with reformat code i guess. But anyway pep8 didn't complain

2017-07-07 11:30 UTC, aTepliak commented on backend/api/projects.py
>  from flask import request, jsonify, make_response, g, Blueprint
ok

2017-07-07 17:38 UTC, DubbleClick commented on backend/__init__.py
> +    ObjectIdField
It's still two imports from mongoengine.fields now. Also pep8 recommends braces, so 

```
from mongoengine.fields import (UUIDField, ListField, StringField, BooleanField, ObjectId
EmbeddedDocumentField, EmbeddedDocument, ListField, ReferenceField)
```

2017-07-10 00:24 UTC, henderkes requested changes

2017-07-10 00:24 UTC, DubbleClick commented on backend/__init__.py
> +class Notification(EmbeddedDocument):
make this DB.EmbeddedDocument please, might throw some errors otherwise

2017-07-10 00:24 UTC, DubbleClick commented on backend/__init__.py
> +    notification_id = DB.ObjectIdField(default=ObjectId)
shouldnt this be 
```notification_id = DB.ObjectIdField(default=ObjectId())```

2017-07-10 00:24 UTC, DubbleClick commented on backend/__init__.py
> +
-- please (newlines)

2017-07-10 00:24 UTC, DubbleClick commented on backend/api/projects.py
> +import uuid
remove this please, its already imported a few lines above

2017-07-10 00:28 UTC, aTepliak commented on backend/api/projects.py
> +import uuid
okay, but I did't do anything with this file

2017-07-10 00:31 UTC, aTepliak commented on backend/__init__.py
> +    notification_id = DB.ObjectIdField(default=ObjectId)
okay, I can try

2017-07-10 00:32 UTC, DubbleClick commented on backend/api/projects.py
> +import uuid
this is a change in this branch though, so should be removed

2017-07-10 00:47 UTC, henderkes submitted a review, later dismissed

2017-07-10 00:59 UTC, henderkes approved these changes

2017-07-10 01:02 UTC, merged