fix bookmark check.
Drakulix/knex pull request #309
Opened 2017-07-12 18:59 UTC by gitmirgut

2017-07-12 19:00 UTC, Rintel approved these changes

2017-07-13 13:47 UTC, markwitz commented
rebase here

2017-07-16 17:08 UTC, henderkes requested changes

2017-07-16 17:08 UTC, DubbleClick commented on web/src/components/views/ProjectContainer.jsx
> +      if(response.status===200){
thats one = too much

2017-07-19 09:56 UTC, closed without merging