Frontend/bugfixes/iss300
Drakulix/knex pull request #310
Opened 2017-07-12 19:01 UTC by Rintel

2017-07-12 22:50 UTC, markwitz submitted a review, later dismissed
rebase plz to not drop backend code

2017-07-13 20:59 UTC, mharasic commented
FINISHED

2017-07-13 21:43 UTC, henderkes reviewed
I have zero knowledge about the frontend or javascript at all, so sorry for the short review.

2017-07-13 21:43 UTC, DubbleClick commented on tests/api/conftest.py
> +        'validexample0_archived.json5'
this was already fixed in the corresponding branch, but whatever

2017-07-13 21:49 UTC, mharasic commented on tests/api/conftest.py
> +        'validexample0_archived.json5'
Came through dirty merge... only a single line

2017-07-14 18:44 UTC, Rintel commented
As I'm the author of the Pull Request, I can't approve it. Therefore one of you should please do it, @Drakulix is waiting for the deployment.

2017-07-15 12:13 UTC, mharasic submitted a review, later dismissed
Sounds working?

2017-07-15 13:28 UTC, mharasic requested changes
See inline comments for 

https://github.com/Drakulix/knex/pull/310/commits/bca2ecb65d9a9ab36d816f57b169baba9dce5220

2017-07-15 13:28 UTC, mharasic commented on web/src/components/views/CreateProjectFromFile.jsx
> +              switch(data.status.toLowerCase()){
status ist mitlerweile analog zum file definiert und ist nicht mehr zahlen basiert

2017-07-15 13:28 UTC, mharasic commented on web/src/components/views/CreateProjectFromFile.jsx
> +              project["date_creation"] = data.date_creation
date_creation is okay.... but ...
date for the datepicker has to be defined as well

2017-07-15 13:31 UTC, mharasic requested changes

2017-07-15 13:31 UTC, mharasic commented on web/src/components/views/CreateProjectFromFile.jsx
> +          status : "2",
Status is now sting based DONE; IN_PROGRESS:...

2017-07-16 16:03 UTC, mharasic approved these changes

2017-07-16 19:04 UTC, merged