[BE] saved search metadata
Drakulix/knex pull request #316
Opened 2017-07-14 15:06 UTC by Drakulix

- Removes unused search apis
- Makes the saved search delete call more consistent with the other delete calls
- Replaces the title field with a metadata field, that can be freely set by the frontend, but is required to be valid json. It's a little dirty to save it internal as a string, but that works around having to specify the concrete and possibly quite complex or even dynamic type of the json.

2017-07-14 16:30 UTC, henderkes requested changes

2017-07-14 16:30 UTC, DubbleClick commented on backend/api/search.py
> +    save = json.loads(request.args.get('save', type=str))
wouldn't json.loads(None) or json.loads("") throw an exception? should handle the case that 'save' is not submitted

2017-07-14 16:30 UTC, DubbleClick commented on backend/api/search.py
> +            return make_response("Success", 200)
Why do we only return a success response for the GET now? This makes no sense.

2017-07-15 14:16 UTC, Drakulix commented on backend/api/search.py
> +            return make_response("Success", 200)
This is clearly a delete call, nothing wrong about it.

2017-07-15 14:16 UTC, Drakulix commented on backend/api/search.py
> +    save = json.loads(request.args.get('save', type=str))
you are right. fixed in the latest commit

2017-07-15 14:23 UTC, henderkes requested changes

2017-07-15 14:23 UTC, DubbleClick commented on backend/api/search.py
> +        return g.save_search(current_user, json.loads(save), request_json, len(projects))
this can still throw an exception and lead to a 500 when the string isn't valid json

2017-07-15 14:23 UTC, DubbleClick commented on backend/api/search.py
> +        return g.save_search(current_user, json.loads(save), request_json, len(projects))
see above

2017-07-15 14:44 UTC, henderkes submitted a review, later dismissed

2017-07-15 14:55 UTC, henderkes approved these changes

2017-07-15 15:11 UTC, merged