Backend/config file
Drakulix/knex pull request #349
Opened 2017-07-19 10:21 UTC by markwitz

resolve #282 

done so far

2017-07-19 13:21 UTC, DubbleClick commented on backend/__init__.py
> +            r"*(@|\sat\s)(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?" + \
please remove the whitespaces

2017-07-19 13:21 UTC, DubbleClick commented on backend/__init__.py
> +config = default_config
We should put the default_config in a seperate file as well in my opinion.

2017-07-19 13:21 UTC, DubbleClick commented on backend/__init__.py
> +                                  })]
Feels harder to read than before

2017-07-19 13:21 UTC, DubbleClick commented on tests/api/test_projects.py
> +        response = enter_default_user_users
why? this is not used anywhere

2017-07-19 13:21 UTC, DubbleClick commented on tests/api/test_projects.py
> +        response = enter_default_user_users
again, why?

2017-07-19 14:08 UTC, Drakulix commented on backend/__init__.py
> +config = default_config
not necessary

2017-07-19 14:12 UTC, Drakulix requested changes
Good stuff, minor nitpicks.

2017-07-19 14:12 UTC, Drakulix commented on backend/__init__.py
> +default_config["administration_user"]["email"] = "admin@knex.com"
You could write that a single literal, that would look much nicer.

2017-07-19 14:12 UTC, Drakulix commented on backend/__init__.py
> +config = default_config
not necessary in my opinion.

2017-07-19 14:12 UTC, Drakulix commented on backend/__init__.py
> +            r"*(@|\sat\s)(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?" + \
Is that a pep8 thing? Seems your editor @markwitz does that all the time?

2017-07-19 14:12 UTC, Drakulix commented on backend/__init__.py
> +                                  })]
Not too important, but @DubbleClick is right.

2017-07-19 14:12 UTC, Drakulix commented on backend/__init__.py
> +    # userpw = hash_password("user")
Please remove, if that is useless now.

2017-07-19 14:12 UTC, Drakulix commented on tests/api/test_projects.py
> +        response = enter_default_user_users
The test requires the user to exist, this just runs the fixture.

2017-07-19 14:12 UTC, Drakulix commented on tests/api/test_projects.py
> +        response = enter_default_user_users
Same. this is good enough for a test.

2017-07-19 22:07 UTC, markwitz commented on tests/api/test_projects.py
> +        response = enter_default_user_users
we could check for the response to be correct here but i just assume it is working correctly

2017-07-19 22:09 UTC, markwitz commented on backend/__init__.py
> +default_config["administration_user"]["email"] = "admin@knex.com"
i'm at a loss here how do i do that?

2017-07-19 22:14 UTC, Drakulix commented on backend/__init__.py
> +default_config["administration_user"]["email"] = "admin@knex.com"
Looks like json, but is valid python syntax:
```python
{
    ...,
    'administration_user': {
        'username': 'admin',
        'password': 'admin',
        'email': 'admin@knex.com',
    }
}
```

2017-07-20 22:26 UTC, henderkes submitted a review, later dismissed
looks good to me now. formatting in on_project_deletion could still be reverted, but it doesn't matter as long as pep8 is happy

2017-07-21 11:54 UTC, Drakulix submitted a review, later dismissed

2017-07-21 14:18 UTC, henderkes approved these changes

2017-07-21 14:18 UTC, merged