Profile shows email now and isAdmin works, I think the problem was th…
Drakulix/knex pull request #353
Opened 2017-07-20 18:15 UTC by JamesComey

…at at the logout, the loaded var was not set to false.
Oh yeah and the profile showas the email now!

2017-07-21 07:33 UTC, Rintel approved these changes

2017-07-21 14:26 UTC, Drakulix commented
Outdated and needs to be updated. Only the profile view change is relevant now that #351 is merged.

2017-07-22 19:01 UTC, henderkes requested changes
Please update it to new master and remove unnecessary changes

2017-07-23 15:43 UTC, DubbleClick commented
Judging by the PR that was just merged, showing email on the profile page I guess this can be closed

2017-07-23 17:36 UTC, closed without merging